### ISSUE TITLE
Upgrade the Levriero Rails version from 5.2 to 6.0

### ISSUE THREAD

**Issue by ashwinisukale** [datacite/levriero#111]

**Comment by wendelfabianchinsamy** [comment]
@ashwinisukale awesome! if you can go directly to 6.1 with relative ease then we certainly give ourselves less work.

**Comment by wendelfabianchinsamy** [comment]
Once this [pr](https://github.com/phusion/passenger-docker/issues/378) is merged into the phusion/passenger-full repo we should be able to go to ruby 3.2.2
