### ISSUE TITLE
Move ES API to production

### ISSUE THREAD

**Issue by kjgarza** [datacite/levriero#13]
- [x] create bulk index rake tasks. depedency #14
- [x] redirect to REST API for other models
- [x] remove commented code
- [x] fix routes in other applications
- [x] include caching

**Comment by kjgarza** [comment]
- We are not gonna use a gateway api. thus get and post methods.
  - one alternative is using nginix with rules.
  - load balancer sent to get or post check further alternatives.
  - or application logic. like before PLEASE NOT.
  - maybe router.

**Comment by kjgarza** [comment]
Validations might need an index manager. consider to check this: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/index_manager.rb

**Comment by kjgarza** [comment]
Validations done

**Comment by kjgarza** [comment]
on using memcaceh https://discuss.elastic.co/t/should-memcached-be-used-with-es/8695/3

**Comment by mfenner** [comment]
We ended up with using different domain names for the ActiveRecord-based API and the Elasticache-based API.
