### ISSUE TITLE
Events sent to the EventData bus contain `subj` and `obj` with incorrect formatting.

### ISSUE THREAD

**Issue by kjgarza** [datacite/levriero#52]
when re-adding event data Bus push  https://github.com/datacite/levriero/pull/51 we included the subj item but in the new default camelCase format. We need to change that.

Actions

1. Stop sending events with the wrong format.
2. Modify events that have been already sent to the eventData bus.

**Comment by mfenner** [comment]
@kjgarza something that would be useful is the resourceTypeGeneral, as this is needed for the Scholix API. I would be ok if that is the only information we include in `subj` and `obj`.

**Comment by mfenner** [comment]
@afandian should we revert back to sending no information in the `subj` and `obj` objects, or should we send the resource_type, which you need for the Scholix API?
