### ISSUE TITLE
Usage report processing broken

### ISSUE THREAD

**Issue by mfenner** [datacite/levriero#66]
Our Dryad dev Scott has been working with Kristian to get the last usage reports in. He noted today 
“I resubmitted all the missing reports again yesterday and I'm still not seeing any of the ones I updated with more results when I query like https://api.datacite.org/events?source-id=datacite-usage&subj-id=https%3A%2F%2Fapi.datacite.org%2Freports%2Fd47d3a5a-7a7a-495a-8db8-d6fb5bba4e5e .”

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_16r0j)

**Comment by kjgarza** [comment]
I think this is not a problem of the logs processing per se but about the EventDat Agent agent consuming usage reports. This operation includes a report parsing. That step is asynchronous and uses a SQS queue; `production_levriero`. Currently, that queue is clogged with 100Ks of CrossrefImport messages coming from new crossref events (the queued crossref events seem to have been there for a while now [12.15.2019]). 

![image](https://user-images.githubusercontent.com/1092861/71092088-db8d9c00-21a6-11ea-95ce-f830a2fcea86.png)

The messages available in the queue do not seem to change, which I guess means the Agent is not consuming anything at the moment.  So it is very likely that the usage reports parsing messages are in that queue waiting, but, they have 100Ks Crossrefimport events in front of them and those messages are not being consumed. 

i hope this helps

**Comment by mfenner** [comment]
There was a bug in the levriero `related_identifier` code that raised an error on processing events `undefined local variable or method `prefix' for RelatedIdentifier:Class`. After fixing this just now via https://github.com/datacite/levriero/commit/0d9eb9c9238c2025d0969b6bf1da7bc04ec8c11c, processing of sqs messages seems to be working properly.

**Comment by mfenner** [comment]
Another problem was that the metrics-api was not running reliably because of low memory settings for the docker container (`256`), and API calls returned a 502 status.

Setting the cpu value for Fargate to `512` fixed the problem.

**Comment by mfenner** [comment]
Will address #114 separately.
