### ISSUE TITLE
Rake tasks to parse usage events broken

### ISSUE THREAD

**Issue by mfenner** [datacite/levriero#68]
`bundle exec rake usage_update:import FROM_DATE=2020-01-01
rake aborted!
NameError: undefined local variable or method `query' for #<UsageUpdate:0x000055e1f4259190>
Did you mean?  to_query`

**Comment by kjgarza** [comment]
this feature was not completely implemented.  https://github.com/datacite/levriero/pull/74 addresses it.

defect: 221x
