### ISSUE TITLE
Create domain for ES supported API

### ISSUE THREAD

**Issue by kjgarza** [datacite/levriero#8]
so we can access this from the outside

**Comment by kjgarza** [comment]
I think this is working already:  https://elastic.test.datacite.org/

but for some weird reasons the name has not changed from `DataCite API` to the new title. IS that just an issue with TTLs @mfenner ?

**Comment by kjgarza** [comment]
Redeployment of docker_host seems to have fixed that. Title has been updated in: https://elastic.test.datacite.org/

please review, @mfenner

**Comment by mfenner** [comment]
Do we want a new domain for the ES-supported API? Or will it live under `api.datacite.org`? In the latter case we need to think how to separate out API calls to `lupo` from those to this API.

In general I prefer to put everything under `api.datacite.org`, but we need to think about how to do this, and we already have three APIs using `api.datacite.org`. I suggest to use this domain for testing, but have this sorted out and use `api.datacite.org` when launching the production service.

**Comment by kjgarza** [comment]
totally I agree on the approach.

We are on testing at the moment. I think full isolation will help us for at this stage.

**Comment by kjgarza** [comment]
can this be closed?
