### ISSUE TITLE
update token 

### ISSUE THREAD

**Issue by kjgarza** [datacite/levriero#86]
[This agent](https://github.com/datacite/mastino/blob/41cfc89767038abdb4123b1dbb4e3b964dfd670a/prod-eu-west/services/crossref-agent/crossref-agent_runner.js) is sending 401 errors:

Datadgo: https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%2C%22log_elb.performance.backend_processing_time%22%2C%22log_duration%22%5D&context_event=AQAAAWl631PIvQdt4wAAAABBV2w2MzJLLVNKc1F4SURrXzRKVg&event&from_ts=1635796993669&index=main&live=true&messageDisplay=inline&query=%40http.status_code%3A401+%40http.url_details.path%3A%22%2Fagents%2Fcrossref%22&stream_sort=desc&to_ts=1638388993669

AWS:
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcrossref-agent

![image](https://user-images.githubusercontent.com/1092861/151112998-a062d9ec-3db3-4269-b340-4ae06d0aa87b.png)

Most likely the token is expired:

https://app.terraform.io/app/datacite-ng/workspaces/prod-eu-west-services-crossref-agent/variables

### After updating the token, the agent will have to be run manually with the rake task to get all the missing data

**Comment by richardhallett** [comment]
What token should this be? an admin JWT?

**Comment by kjgarza** [comment]
Fixed, I added also the exp date into the Terraform config so people can tell when it needs to be updated
